name: tallman_ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # Updated to a stable version of Python
  - streamlit=1.21.0  # Updated to the latest version of Streamlit
  - chromadb=0.3.21  # Added version for ChromaDB
  - python-dotenv=1.0.0  # Updated to the latest version of python-dotenv
  - pandas=2.0.1  # Added version for pandas
  - spacy=3.5.2  # Added version for spaCy
  - nltk=3.8.1  # Added version for NLTK
  - python-dotenv=1.0.1
  - scikit-learn=1.2.2  # Added version for scikit-learn
  - pip
  - pip:
    - en-core-web-sm==3.5.0  # spaCy English model
    - groq  # Added groq package
    - python-dotenv
    - chromadbr

# Add other dependencies...
